# This file will be dynamically updated by the promotion-to-commit workflow.
# The initial values are placeholders.
restart_timestamp: "1678886401"
prod_docker_repo: "bookverse-docker-external"
services:
  inventory:
    port: 30001
    frontend:
      image: productdemo.jfrog.io/bookverse-docker-external/inventory-service-frontend/1.3.31
    backend:
      image: productdemo.jfrog.io/bookverse-docker-external/inventory-service-backend/1.3.31
  recommendations:
    port: 30002
    frontend:
      image: productdemo.jfrog.io/bookverse-docker-external/recommendations-service-frontend/1.3.2
    backend:
      image: productdemo.jfrog.io/bookverse-docker-external/recommendations-service-backend/1.3.2
  checkout:
    port: 30003
    frontend:
      image: productdemo.jfrog.io/bookverse-docker-external/checkout-service-frontend/1.3.2
    backend:
      image: productdemo.jfrog.io/bookverse-docker-external/checkout-service-backend/1.3.2
