# This file will be dynamically updated by the promotion-to-commit workflow.
# The initial values are placeholders.
restart_timestamp: "1678886401"
prod_docker_repo: "bookverse-docker-external-prod"
services:
  inventory:
    port: 30001
    frontend:
      image: 'productdemo.jfrog.io/bookverse-docker-external-prod/inventory-service-frontend:1.3.148'
    backend:
      image: 'productdemo.jfrog.io/bookverse-docker-external-prod/inventory-service-backend:1.3.148'
  recommendations:
    port: 30002
    frontend:
      image: 'productdemo.jfrog.io/bookverse-docker-external-prod/recommendations-service-frontend:1.3.21'
    backend:
      image: 'productdemo.jfrog.io/bookverse-docker-external-prod/recommendations-service-backend:1.3.21'
  checkout:
    port: 30003
    frontend:
      image: 'productdemo.jfrog.io/bookverse-docker-external-prod/checkout-service-frontend:1.3.25'
    backend:
      image: 'productdemo.jfrog.io/bookverse-docker-external-prod/checkout-service-backend:1.3.25'
